[package]
name = "pc_speaker_music"
version = "0.1.0"
edition = "2021"
authors = ["Beep Lover"]
description = "Play classic tunes through PC speaker"

[dependencies]
libc = "0.2"
nix = "0.26.2"
ctrlc = "3.2.5" 